[project]
name = "taskflows"
version = "0.7.2"
description = "Python task management, scheduling, alerts."
authors = [{ name = "Dan Kelleher", email = "kelleherjdan@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
readme = "README.md"

dependencies = [
    "sqlalchemy>=2.0.0",
    "pydantic>=2.0.0",
    "tqdm",
    "click",
    "rich",
    "docker",
    "dynamic-imports>=1.0.0",
    "alert-msgs>=0.5.0",
    "quicklogs>=1.1.0",
    "func-timeout>=4.0.0",
]

[tool.setuptools]
packages = ["taskflows"]

[project.optional-dependencies]
service = ["python-dotenv", "docker", "dbus-python"]
dev = ["black", "pytest", "pytest-asyncio", "psycopg[binary]"]

[build-system]
requires = ["setuptools>=43.0.0", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
taskflows = 'taskflows.admin:cli'
_taskflows_call = 'taskflows.service.commands:_taskflows_call'
