# File: .github/workflows/publish-on-version-bump.yml
name: Publish to PyPI on version bump

on:
  push:
    paths:
      - 'pyproject.toml'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # required for trusted publishing.
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Python Package New Version
        uses: MathieuMoalic/action-python-package-new-version@v1.0.1

      - name: Set up Python
        if: env.PUBLISHING == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        if: env.PUBLISHING == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distributions
        if: env.PUBLISHING == 'true'
        run: python -m build

      - name: Publish to PyPI
        if: env.PUBLISHING == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1